misconfigurations:
  - id: AVD-AWS-0057
    paths:
      - "iam.tf"
    statement: "Intentionally allowing assuming into all terraform roles in all AWS accounts"
  - id: AVD-AWS-0132
    paths:
      - "../../modules/s3-bucket/s3-bucket.tf"
    statement: "We have to use a AWS managed key for log target bucket"
  - id: AVD-AWS-0017
    paths:
      - "../../modules/compliant-organization/cloudtrail.tf"
    statement: "We are using an AWS managed key for the cloudtrail bucket"
  - id: AVD-AWS-0101
    paths:
      - "../../modules/compliant-account/vpc.tf"
    statement: "We use the default vpc only to disable things in it"
