name: tflint
on: [push]
jobs:
  run-tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.46.1
      - name: Initialize tflint
        run: |
          cd tenants/management && tflint --init
      - name: Run tflint
        run: |
          cd tenants/management && tflint -f compact
