name: tflint
on: [push]
jobs:
  run-tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.1
      - name: Initialize tflint
        run: |
          find tenants/ -type f -name 'main.tf' -exec \
            bash -c 'for f; do tflint --init $(dirname "$f"); done' _ {} +
      - name: Run tflint
        run: |
          find tenants/ -type f -name 'main.tf' -exec \
            bash -c 'for f; do tflint -f compact $(dirname "$f"); done' _ {} +