name: trivy
on: [push]
jobs:
  run-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: trivy
        uses: aquasecurity/trivy-action@master
        with:
          github_token: ${{ github.token }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
